-- dynamic aim reticle: 4 rotated copies of a single "corner of a circle" texture
-- (materials/beatrun/gears/grappler/crosshair_corner.png, generated by crosshair_proto.py), all
-- drawn centered on the same point so they read as one circle. Size reacts to a live aim
-- raycast (clamped between the gear's min/max range) -- kept subtle (MIN/MAX_RADIUS_PX close
-- together) plus a brief size pulse on fire. As the raycast gets close to max_range, alpha
-- smoothly fades as a proximity warning, on top of (and independent from) the full spin+fade
-- that plays once it's actually confirmed unreachable. Purely a local-player HUD effect -- no
-- gameplay impact.
--
-- Receives the grappler's own client.lua module table via mod.Init() instead of calling
-- gearsHandler.GetClientGear("grappler") itself every frame -- include() never caches, so a
-- fresh GetClientGear call from here would re-include client.lua (which includes this very
-- file), re-registering this hook with zeroed-out state every single frame forever.
local mod = {}

local gearMod

function mod.Init(theGearMod)
  gearMod = theGearMod
end

local crosshairMat = Material("beatrun/gears/grappler/crosshair_corner.png", "noclamp smooth")

-- must match crosshair_proto.py's RADIUS_FRACTION -- how big the arc's radius is relative to
-- the texture's own half-size, so we can size the drawn rect to hit a specific on-screen radius
local TEXTURE_RADIUS_FRACTION = 0.5

local PIVOTS_DEG = { 0, 90, 180, 270 }
local MIN_RADIUS_PX = 17
local MAX_RADIUS_PX = 24 -- kept close to MIN_RADIUS_PX -- a subtler range-size effect than before
local OPEN_PUSH_PX = 10
local OPEN_DECAY_TIME = 0.35

local RANGE_FADE_START = 0.7 -- start fading once this far (0-1) toward max_range
local RANGE_FADE_MIN_ALPHA = 90 -- alpha floor from proximity fade alone (full fade needs actually-unreachable)

local UNREACHABLE_ANIM_DURATION = 0.35 -- how long the spin+fade takes to fully play out
local MISS_DEBOUNCE = 0.1 -- how long with zero hits before we start counting as unreachable
local HIT_DEBOUNCE = 0.1 -- how long with continuous hits before a stray miss-streak is cancelled

local baseRotation = 0
local openTriggerTime = -math.huge

-- a single stray hit/miss frame shouldn't instantly flip the state -- both directions need to
-- sustain briefly before they count
local hitStreak = 0
local missStreak = 0
local unreachableElapsed = 0 -- seconds continuously (confirmed) unreachable

function mod.TriggerOpen()
  openTriggerTime = CurTime()
end

hook.Add("HUDPaint", "BeatrunGrapplerCrosshair", function()
  local ply = LocalPlayer()
  if not IsValid(ply) or ply:GetNW2String("brgear_left", "") ~= "grappler" then
    hitStreak = 0
    missStreak = 0
    unreachableElapsed = 0
    return
  end

  if ply:GetNW2Bool("brgear_grapple_active", false) then return end

  if gearMod == nil or gearMod.config == nil then return end

  local startPos = ply:EyePos()
  local dir = ply:EyeAngles():Forward()

  local trace = util.TraceLine({
    start = startPos,
    endpos = startPos + dir * gearMod.config.max_range,
    filter = ply
  })

  local reachable = trace.Hit
  local distance = reachable and startPos:Distance(trace.HitPos) or gearMod.config.max_range
  distance = math.Clamp(distance, gearMod.config.min_range, gearMod.config.max_range)

  if reachable then
    hitStreak = hitStreak + FrameTime()
    missStreak = 0
  else
    missStreak = missStreak + FrameTime()
    hitStreak = 0
  end

  -- only a SUSTAINED hit streak cancels the animation -- an isolated stray hit frame won't
  -- reset unreachableElapsed, so it can actually finish playing instead of restarting forever
  if hitStreak >= HIT_DEBOUNCE then
    unreachableElapsed = 0
  elseif missStreak >= MISS_DEBOUNCE then
    unreachableElapsed = unreachableElapsed + FrameTime()
  end

  local unreachableT = math.Clamp(unreachableElapsed / UNREACHABLE_ANIM_DURATION, 0, 1)
  local rotationOffset = Lerp(unreachableT, baseRotation, baseRotation + 180)
  local unreachableAlpha = Lerp(unreachableT, 255, 0)

  local t = (distance - gearMod.config.min_range) / (gearMod.config.max_range - gearMod.config.min_range)
  local radius = Lerp(t, MIN_RADIUS_PX, MAX_RADIUS_PX)

  -- proximity-to-max-range fade: a smooth warning fade that starts before it's actually
  -- confirmed unreachable, separate from (and combined with) unreachableAlpha above
  local rangeAlpha = 255
  if t > RANGE_FADE_START then
    local fadeT = (t - RANGE_FADE_START) / (1 - RANGE_FADE_START)
    rangeAlpha = Lerp(fadeT, 255, RANGE_FADE_MIN_ALPHA)
  end

  local alpha = math.min(unreachableAlpha, rangeAlpha)

  local openAmount = 1 - math.Clamp((CurTime() - openTriggerTime) / OPEN_DECAY_TIME, 0, 1)
  local pieceRadius = radius + openAmount * OPEN_PUSH_PX
  local drawSize = (pieceRadius / TEXTURE_RADIUS_FRACTION) * 2

  local centerX, centerY = ScrW() / 2, ScrH() / 2

  surface.SetMaterial(crosshairMat)
  surface.SetDrawColor(255, 255, 255, alpha)

  for _, pivotDeg in ipairs(PIVOTS_DEG) do
    surface.DrawTexturedRectRotated(centerX, centerY, drawSize, drawSize, pivotDeg + rotationOffset)
  end
end)

return mod
